# Generated by Django 5.1 on 2024-08-22 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_name",
                    models.CharField(max_length=100, verbose_name="分类名称"),
                ),
                ("description", models.TextField(blank=True, verbose_name="分类描述")),
                (
                    "image",
                    models.ImageField(
                        default="category_images/default.jpg",
                        upload_to="category_images/",
                        verbose_name="分类图片",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="订单时间"),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="总金额"
                    ),
                ),
                ("order_status", models.CharField(max_length=50, verbose_name="订单状态")),
                ("pay", models.BooleanField(default=False, verbose_name="支付")),
            ],
        ),
        migrations.CreateModel(
            name="ShoppingCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(max_length=50, verbose_name="支付方式"),
                ),
                (
                    "payment_status",
                    models.CharField(max_length=50, verbose_name="支付状态"),
                ),
                (
                    "payment_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="支付时间"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CommerceCore.order",
                        verbose_name="订单",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "product_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="商品ID"
                    ),
                ),
                ("product_name", models.CharField(max_length=100, verbose_name="商品名称")),
                (
                    "image",
                    models.ImageField(
                        default="category_images/default.jpg",
                        upload_to="product_images/",
                        verbose_name="商品图片",
                    ),
                ),
                ("click", models.IntegerField(default=0, verbose_name="点击量")),
                (
                    "unit",
                    models.CharField(
                        default="500g", max_length=20, verbose_name="单位重量"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="商品描述")),
                ("details", models.TextField(blank=True, verbose_name="商品详情")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="价格"
                    ),
                ),
                ("stock_quantity", models.IntegerField(verbose_name="库存数量")),
                (
                    "listing_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="上架时间"),
                ),
                ("suggest", models.BooleanField(default=False, verbose_name="推荐")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CommerceCore.category",
                        verbose_name="类别",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="数量")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="单价"
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="总价"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="地址"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CommerceCore.order",
                        verbose_name="订单",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CommerceCore.product",
                        verbose_name="商品",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1, verbose_name="数量")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CommerceCore.product",
                        verbose_name="商品",
                    ),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CommerceCore.shoppingcart",
                        verbose_name="购物车",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=50, unique=True, verbose_name="用户名称"),
                ),
                ("sex", models.CharField(blank=True, max_length=10, verbose_name="性别")),
                ("password", models.CharField(max_length=255, verbose_name="密码")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, unique=True, verbose_name="邮箱"
                    ),
                ),
                ("phone_number", models.CharField(max_length=20, verbose_name="电话号码")),
                (
                    "tel",
                    models.CharField(blank=True, max_length=20, verbose_name="联系方式"),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="地址"
                    ),
                ),
                (
                    "registration_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="注册时间"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="shoppingcart",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.CreateModel(
            name="GoodsBrowser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "browse_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="浏览时间"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CommerceCore.product",
                        verbose_name="商品",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
        ),
    ]
