# Generated by Django 5.1 on 2024-08-25 23:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CommerceCore", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="number",
            field=models.BigAutoField(
                primary_key=True, serialize=False, verbose_name="订单号"
            ),
        ),
    ]
