# Generated by Django 5.1 on 2024-08-18 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CommerceCore", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                default="category_images/default.jpg",
                upload_to="category_images/",
                verbose_name="分类图片",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="pay",
            field=models.BooleanField(default=False, verbose_name="支付"),
        ),
        migrations.AddField(
            model_name="orderdetail",
            name="address",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="地址"
            ),
        ),
        migrations.AddField(
            model_name="orderdetail",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="总价"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="click",
            field=models.IntegerField(default=0, verbose_name="点击量"),
        ),
        migrations.AddField(
            model_name="product",
            name="details",
            field=models.TextField(blank=True, verbose_name="商品详情"),
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default="category_images/default.jpg",
                upload_to="product_images/",
                verbose_name="商品图片",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="suggest",
            field=models.BooleanField(default=False, verbose_name="推荐"),
        ),
        migrations.AddField(
            model_name="product",
            name="unit",
            field=models.CharField(default="500g", max_length=20, verbose_name="单位重量"),
        ),
        migrations.AddField(
            model_name="user",
            name="sex",
            field=models.CharField(blank=True, max_length=10, verbose_name="性别"),
        ),
        migrations.AddField(
            model_name="user",
            name="tel",
            field=models.CharField(blank=True, max_length=20, verbose_name="联系方式"),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="CommerceCore.shoppingcart",
                verbose_name="购物车",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="CommerceCore.product",
                verbose_name="商品",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.IntegerField(verbose_name="数量"),
        ),
        migrations.AlterField(
            model_name="category",
            name="category_name",
            field=models.CharField(max_length=100, verbose_name="分类名称"),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, verbose_name="分类描述"),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="订单时间"),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.CharField(max_length=50, verbose_name="订单状态"),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="总金额"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="CommerceCore.user",
                verbose_name="用户",
            ),
        ),
        migrations.AlterField(
            model_name="orderdetail",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="CommerceCore.order",
                verbose_name="订单",
            ),
        ),
        migrations.AlterField(
            model_name="orderdetail",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="CommerceCore.product",
                verbose_name="商品",
            ),
        ),
        migrations.AlterField(
            model_name="orderdetail",
            name="quantity",
            field=models.IntegerField(verbose_name="数量"),
        ),
        migrations.AlterField(
            model_name="orderdetail",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="单价"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="CommerceCore.order",
                verbose_name="订单",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="支付时间"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(max_length=50, verbose_name="支付方式"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_status",
            field=models.CharField(max_length=50, verbose_name="支付状态"),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="CommerceCore.category",
                verbose_name="类别",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, verbose_name="商品描述"),
        ),
        migrations.AlterField(
            model_name="product",
            name="listing_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="上架时间"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="价格"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_name",
            field=models.CharField(max_length=100, verbose_name="商品名称"),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock_quantity",
            field=models.IntegerField(verbose_name="库存数量"),
        ),
        migrations.AlterField(
            model_name="shoppingcart",
            name="creation_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="shoppingcart",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="CommerceCore.user",
                verbose_name="用户",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="地址"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, unique=True, verbose_name="邮箱"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=255, verbose_name="密码"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(max_length=20, verbose_name="电话号码"),
        ),
        migrations.AlterField(
            model_name="user",
            name="registration_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="注册时间"),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=50, unique=True, verbose_name="用户名称"),
        ),
        migrations.CreateModel(
            name="GoodsBrowser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "browse_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="浏览时间"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CommerceCore.product",
                        verbose_name="商品",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CommerceCore.user",
                        verbose_name="用户",
                    ),
                ),
            ],
        ),
    ]
