# Generated by Django 5.1 on 2024-08-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CommerceCore", "0002_alter_order_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="score_total",
            field=models.IntegerField(default=0, verbose_name="总评分"),
        ),
    ]
