# Generated by Django 5.1 on 2024-08-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CommerceCore", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="score",
            field=models.IntegerField(default=0, verbose_name="评分"),
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                default="avatars/default.png",
                upload_to="category_images/",
                verbose_name="分类图片",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default="avatars/default.png",
                upload_to="product_images/",
                verbose_name="商品图片",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                default="avatars/default.png", upload_to="avatars/", verbose_name="头像"
            ),
        ),
    ]
