# Generated by Django 5.1 on 2024-08-23 22:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CommerceCore", "0003_product_score_alter_category_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sales",
            field=models.IntegerField(default=0, verbose_name="销量"),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit",
            field=models.CharField(default="不计重量", max_length=20, verbose_name="单位重量"),
        ),
    ]
