# Generated by Django 5.1 on 2024-08-23 22:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CommerceCore", "0004_product_sales_alter_product_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="rating_count",
            field=models.IntegerField(default=0, verbose_name="评分人数"),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit",
            field=models.CharField(default="个", max_length=20, verbose_name="单位"),
        ),
    ]
