# Generated by Django 5.1 on 2024-08-24 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CommerceCore", "0005_product_rating_count_alter_product_unit"),
    ]

    operations = [
        migrations.CreateModel(
            name="FavoriteList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FavoriteItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="收藏时间"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CommerceCore.product",
                        verbose_name="商品",
                    ),
                ),
                (
                    "favorite_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CommerceCore.favoritelist",
                        verbose_name="收藏列表",
                    ),
                ),
            ],
        ),
    ]
