# Generated by Django 5.1 on 2024-08-25 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CommerceCore", "0008_remove_order_pay_remove_orderdetail_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="is_paid",
        ),
        migrations.RemoveField(
            model_name="order",
            name="payment_status",
        ),
        migrations.AddField(
            model_name="orderdetail",
            name="discount",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="折扣"
            ),
        ),
        migrations.AddField(
            model_name="orderdetail",
            name="product_name",
            field=models.CharField(
                default="Unnamed Product", max_length=100, verbose_name="商品名称"
            ),
        ),
        migrations.AddField(
            model_name="orderdetail",
            name="tax",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="税额"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("awaiting_payment", "Awaiting Payment"),
                    ("payment_failed", "Payment Failed"),
                    ("shipped", "Shipped"),
                    ("out_for_delivery", "Out for Delivery"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                    ("refunded", "Refunded"),
                    ("return_requested", "Return Requested"),
                    ("returned", "Returned"),
                    ("awaiting_pickup", "Awaiting Pickup"),
                ],
                default="pending",
                max_length=20,
                verbose_name="订单状态",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="CommerceCore.category",
                verbose_name="类别",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_name",
            field=models.CharField(
                default="Unnamed Product", max_length=100, verbose_name="商品名称"
            ),
        ),
    ]
