# Generated by Django 5.1 on 2024-08-25 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "CommerceCore",
            "0009_remove_order_is_paid_remove_order_payment_status_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.CharField(
                blank=True, default="未填写", max_length=255, verbose_name="地址"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(default="未填写", max_length=20, verbose_name="电话号码"),
        ),
        migrations.AlterField(
            model_name="user",
            name="sex",
            field=models.CharField(
                blank=True, default="未填写", max_length=10, verbose_name="性别"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="tel",
            field=models.CharField(
                blank=True, default="未填写", max_length=20, verbose_name="联系方式"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(blank=True, default="未填写", verbose_name="个人简介"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="birthdate",
            field=models.DateField(
                blank=True,
                default=datetime.date(2000, 1, 1),
                null=True,
                verbose_name="生日",
            ),
        ),
    ]
